### ISSUE TITLE
how to convert model with multiple outputs

### ISSUE THREAD

**Issue by Jackyangyang** [james77777778/darknet-onnx#4]
Sir ,How to convert yolov4 model with three outputs ?

**Comment by james77777778** [comment]
Hi @Jackyangyang,
It is hard to debug without details. Could you share your darknet config (`.cfg`) with three outputs?

You can also try `export_to_onnx` in https://github.com/james77777778/darknet-onnx/blob/master/darknetonnx/darknet.py#L17 which only cares about model architecture and should support valid darknet cfg file.

**Comment by james77777778** [comment]
Closing since staled
