### ISSUE TITLE
Error in post processing

### ISSUE THREAD

**Issue by PrajwalCogniac** [james77777778/darknet-onnx#5]
Hey guys thanks a lot for this repo ! I really liked it ! but I am getting the following error in postprocessing !
Please help me solve this !
![image](https://user-images.githubusercontent.com/99682235/225813242-ce3ff13a-82e4-4b74-9a11-ccccae6319f1.png)

So more info ! This is my yolo4.cfg and it has 6 output classes , so the output from Neural network is perfect (1,nums,4+6)
But when I do the detect function I am getting the above error ! Please let me know if you need more info

**Comment by james77777778** [comment]
Hi @PrajwalCogniac 

It is hard to tell where the error from without further information. Could you provide the shape of `valid_score_mask` and `boxes`?

Do you run the script exactly from this repo? (including the requirements stated in README.md)

**Comment by james77777778** [comment]
This repo is kind of out-dated. I will try to update it when I'm available.

EDITED:
I updated some requirements and the model conversion worked as expected:

```bash
python3 main.py --cfg cfg/yolov4.cfg --weight weights/yolov4.weights --img data/dog.jpg --names data/coco.names
```

**Comment by james77777778** [comment]
Hi @PrajwalCogniac 

Feel free to reopen it if the issue persists.
